The Defense Speech ("Apology") of Socrates*
Minor corrections in the text were made February 1, 2012.

Introduction by Manuel Velasquez
Note by Dr. Garrett: I have provided study questions for this version of the Defense Speech as well as the longer version. (Note added February 7, 2011)

Socrates' relentless and, to some people, infuriating questioning of his fellow citizens eventually led to his death. Shortly after the scene described in Euthyphro, Meletus and others indicted Socrates and brought him to trial. In his brilliant work The Apology, Plato summarized the speech Socrates delivered in his defense. The speech is especially fascinating because it provides a summary of Socrates' life and of his devotion to philosophical questioning. Socrates is standing in court, facing the jury composed of five hundred Athenian citizens who have just heard the testimony of his accusers, who charge him with corrupting the youth of Athens and with not believing in the gods of the state:

[From The Apology of Socrates, translated (and much abridged) by Manuel Velasquez (copyright 1987); for a full translation, by Benjamin Jowett, see Jowett Translation.--J.G.]

I do not know, my fellow Athenians, how you were affected by my accusers whom you just heard. But they spoke so persuasively they almost made me forget who I was. Yet they hardly uttered a word of truth.
But many of you are thinking, "Then what is the origin of these accusations, Socrates?" That is a fair question. Let me explain their origins— Some of you know my good friend Chaerephon. Before he died he went to Delphi and asked the religious oracle there to tell him who the wisest man in the world was. The oracle answered that there was no man wiser than Socrates.

When I learned this, I asked myself, "What can the god's oracle mean?" For I knew I had no wisdom. After thinking it over for a long time, I decided that I had to find a man wiser than myself so I could go back to the god's oracle with this evidence. So I went to see a politician who was famous for his wisdom. But when I questioned him, I realized he really was not wise, although many people—he especially—thought he was. So I tried to explain to him that although he thought himself wise, he really was not. But all that happened was that he came to hate me. And so did many of his supporters who overheard us. So I left him, thinking to myself as I left that although neither of us really knew anything about what is noble and good, still I was better off. For he knows nothing, and thinks that he knows, while I neither know nor think that I know. And in this I think I have a slight advantage.

Then I went to another person who had even greater pretensions to wisdom. The result was exactly the same: I made another enemy. In this way I went to one man after another and made more and more enemies. I felt bad about this and it frightened me. But I was compelled to do it because I felt that investigating god's oracle came first. I said to myself, I must go to everyone who seems to be wise so I can find out what the oracle meant.

My hearers imagine that I myself possess the wisdom which I find lacking in others. But the truth is, Men of Athens, that only god is wise. And by his oracle he wanted to show us that the wisdom of men is worth little or nothing. It is as if he was telling us, "The wisest man is the one who, like Socrates, knows that his wisdom is in truth worth nothing." And so I go about the world obedient to god. I search and question the wisdom of anyone who seems to be wise. And if he is not wise, then to clarify the meaning of the oracle I show him that he is not wise. My occupation completely absorbs me and I have no time for anything else. My devotion to the god has reduced me to utter poverty.

There is something more. Young men of the richer classes, who do not have much to do, follow me around of their own accord. They like to hear pretenders exposed. And sometimes they imitate me by examining others themselves. They quickly discover that there are plenty of people who think they know something but who really know nothing at all. Then those people also get angry at me. "This damnable Socrates is misleading our youth!" they say. And if somebody asks them, "How? What evil things does he do or teach them?" they cannot say.

But in order not to appear at a loss, these people repeat the charges used against all philosophers: that we teach obscure things up in the clouds, that we teach atheism, and that we make the worst views appear to be the best. For people do not like to admit that their pretensions to knowledge have been exposed. And that, fellow Athenians, is the origin of the prejudices against me.

But some of you will ask, "Don't you regret what you did since now it might mean your death?" To these I answer, "You are mistaken. A good man should not calculate his chances of living or dying. He should only ask himself whether he is doing right or wrong—whether his inner self is that of a good man or of an evil one."

And if you say to me, "Socrates, we will let you go free but only on condition that you stop your questioning," then I will reply, "Men of Athens, I honor and love you. But I must obey god rather than you, and while I have life and strength I will never stop doing philosophy." For my aim is to persuade you all, young and old alike, not to think about your lives or your properties, but first and foremost to care about your inner self. I tell you that wealth does not make you good within, but that from inner goodness comes wealth and every other benefit to man. This is my teaching, and if it corrupts youth, then I suppose I am their corrupter.

Well, my fellow Athenians, you must now decide whether to acquit me or not. But whichever you do, understand that I will never change my ways, not even if I have to die many rimes. To talk daily about what makes us good, and to question myself and others, is the greatest thing man can do. For the unexamined life is not worth living.

[At this point Socrates rested his case. The jury debated among themselves and then, in a split vote, they reached their final verdict.]

Men of Athens, you have condemned me to death. To those of you who are my friends and who voted to acquit me let me say that death may be a good thing. Either it is a state of nothingness and utter unconsciousness, or, as some people say, it is merely a migration from this world to another. If it is complete unconsciousness— like a sleep undisturbed even by dreams—then death will be an unspeakable gain. And if it is a journey to anodier world where all the dead live, then it will also be a great good. For then I can continue my search into true and false knowledge: In the next world, as in this one, I can continue questioning the great people of the past to find out who is wise and who merely pretends to be. So do not be saddened by death. No evil can happen to a good man either in this life or in death.

Well, the hour of departure has arrived, and we must each go our ways. I to die, and you to live. Which is better only god knows.

Closing Comment by Velasquez
Again, Socrates' speech provides a remarkable example of what philosophy is. Philosophy is the quest for wisdom: an unrelenting devotion to uncover the truth about what matters most in one's life. This quest is undertaken in the conviction that a life based on an easy, uncritical acceptance of conventional beliefs is an empty life. As Socrates puts it, "The unexamined life is not worth living." Philosophy is a quest that is difficult, not only because it requires hard thinking but also because it sometimes requires taking positions that are not shared by those around us.
* This material is based on Velasquez, Philosophy: A Text with Readings, 10th edition. It essentially duplicates pp. 22-23 of the Custom Edition textbook for PHIL 120 that was used in Spring 2009. (1/25/09)—Dr. Garrett